---
title: "Data 608 - Final Project"
author: "Leticia Salazar"
date: "December 11, 2022"
output:
  html_document:
    theme: united
    highlight: kate
  html_notebook: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

$~$    

# Polycystic Ovarian Syndrome (PCOS)

```{r, warning=FALSE, message=FALSE}
library(tidyverse)
library(dplyr)
library(corrplot)
library(DataExplorer)
library(hrbrthemes)
library(ggplot2)

library(rsconnect)
library(plotly)
library(shiny)
```

```{r, echo=FALSE}
pcos <- read.csv("https://raw.githubusercontent.com/letisalba/DATA_608/master/Final%20Project/csv/PCOS_infertility.csv")
pcos_infertility <- read.csv("https://raw.githubusercontent.com/letisalba/DATA_608/master/Final%20Project/csv/PCOSData_without_infertility.csv")
```

```{r, echo=FALSE}
head(pcos, 4)
```

```{r, echo=FALSE}
head(pcos_infertility, 4)
```

```{r, echo=FALSE}
glimpse(pcos)
```

```{r, echo=FALSE}
glimpse(pcos_infertility)
```

```{r}
# pcos < -mutate_all(pcos, function(x) as.numeric(as.character(x)))
# pcos_infertility <- mutate_all(pcos_infertility, function(x) as.numeric(as.character(x)))
```

```{r}
colnames(pcos)
```

```{r}
colnames(pcos_infertility)
```

```{r}
# merge data sets
pcos_data <- merge(pcos, pcos_infertility,  by=c("Sl..No"))
head(pcos_data)
```


```{r}
# dropping columns
pcos_data <- dplyr::select(pcos_data, -c(1:2,7:8,50))
head(pcos_data)
```


```{r}
colSums(is.na(pcos_data))
```


```{r}
# pcos_data <- round(mutate_all(pcos_data, function(x) as.numeric(as.character(x))),2)

#as.data.frame(pcos_data)
```

```{r}
ggplot(pcos_data, aes(x=pcos_data$"Age..yrs.", y=pcos_data$"Weight..Kg.")) +
    geom_point() +
  theme_ipsum() +
    theme(
      plot.title = element_text(size=10)
    )
```


```{r}
# # convert Height from cm to m
# pcos_data$"Height(Cm)" <- round((pcos_data$"Height(Cm)" * 0.01),1)
# 
# pcos_data <- pcos_data %>% 
#   rename("Height(M)" = "Height(Cm)")
# 
# # calculate BMI
# pcos_data$BMI <- round((pcos_data$"Weight(Kg)" / pcos_data$"Height(M)"^2), 1)
# 
# # calculate waist-hip ratio
# pcos_data$"Waist-Hip Ratio" <- round((pcos_data$"Waist(inch)" / pcos_data$"Hip(inch)"),2)
# 
# # calculate FSH/LH
# pcos_data$"FSH/LH" <- round((pcos_data$"FSH(mIU/mL)"/pcos_data$"LH(mIU/mL)"),2)
# 
# # calculate Marriage Status
# pcos_data$"Marriage Status(Yrs)"[is.na(pcos_data$"Marriage Status(Yrs)")] <- median(pcos_data$"Marriage Status(Yrs)", na.rm = T)
# 
# # calculate Fast food
# pcos_data$"Fast food(Y/N)"[is.na(pcos_data$"Fast food(Y/N)")] <- median(pcos_data$"Fast food(Y/N)", na.rm = T)
# 
# # calculate 
# pcos_data$"AMH(ng/mL)"[is.na(pcos_data$"AMH(ng/mL)")] <- median(pcos_data$"AMH(ng/mL)", na.rm = T)
```






```{r, echo=FALSE}
# # removing first two column for `pcos` data
# # pcos <- dplyr::select(pcos, -c(1:2)) 
# pcos <- dplyr::select(pcos, -c(2))
# 
# # renaming columns for `pcos` data
# pcos <- pcos %>% 
#   rename("Sl.No" = "Sl..No",
#          "PCOS(Y/N)" = "PCOS..Y.N.",
#          "I beta-HCG(mIU/mL)" = "I...beta.HCG.mIU.mL.",
#          "II beta-HCG(mIU/mL)" = "II....beta.HCG.mIU.mL.",
#          "AMH(ng/mL)" = "AMH.ng.mL." )
# 
# # removing columns not needed for `pcos_infertility` data
# #pcos_infertility <- dplyr::select(pcos_infertility, -c(1:2, 17:18, 26, 45))
# pcos_infertility <- dplyr::select(pcos_infertility, -c(2, 17:18, 26, 45))
# 
# # renaming columns for `pcos_infertility` data
# pcos_infertility <- pcos_infertility %>% 
#   rename("Sl.No" = "Sl..No",
#          "PCOS(Y/N)" = "PCOS..Y.N.",
#          "Age(Yrs)" = "Age..yrs.",
#          "Weight(Kg)" = "Weight..Kg.",
#          "Height(Cm)" = "Height.Cm.",
#          "Blood Group" = "Blood.Group", 
#          "Pulse rate(bpm)" = "Pulse.rate.bpm.",
#          "RR(breaths/min)" = "RR..breaths.min.",
#          "Hb(g/dl)" = "Hb.g.dl.",
#          "Cycle(R/I)" = "Cycle.R.I.",
#          "Cycle length(days)" = "Cycle.length.days.",
#          "Marriage Status(Yrs)" = "Marraige.Status..Yrs.",
#          "Pregnant(Y/N)" = "Pregnant.Y.N.",
#          "No. of aborptions" = "No..of.aborptions",
#          "FSH(mIU/mL)" = "FSH.mIU.mL.",
#          "LH(mIU/mL)" = "LH.mIU.mL.",
#          "FSH/LH" = "FSH.LH",
#          "Hip(inch)" = "Hip.inch.",
#          "Waist(inch)" = "Waist.inch.",
#          "Waist-Hip Ratio" = "Waist.Hip.Ratio",
#          "TSH(mIU/L)" = "TSH..mIU.L.",
#          "PRL(ng/mL)" = "PRL.ng.mL.",
#          "Vit D3(ng/mL)" = "Vit.D3..ng.mL.",
#          "PRG(ng/mL)" = "PRG.ng.mL.",
#          "RBS(mg/dl)" = "RBS.mg.dl.",
#          "Weight gain(Y/N)" = "Weight.gain.Y.N.",
#          "hair growth(Y/N)" = "hair.growth.Y.N.",
#          "Skin darkening(Y/N)" = "Skin.darkening..Y.N.",
#          "Hair loss(Y/N)" = "Hair.loss.Y.N.",
#          "Pimples(Y/N)" = "Pimples.Y.N.",
#          "Fast food(Y/N)" = "Fast.food..Y.N.",
#          "Reg.Exercise(Y/N)" = "Reg.Exercise.Y.N.",
#          "BP Systolic(mmHg)" = "BP._Systolic..mmHg.",
#          "BP Diastolic(mmHg)" = "BP._Diastolic..mmHg.",
#          "Follicle No.(L)" = "Follicle.No...L.",
#          "Follicle No.(R)" = "Follicle.No...R.",
#          "Avg. F size(L)(mm)" = "Avg..F.size..L...mm.",
#          "Avg. F size(R)(mm)" = "Avg..F.size..R...mm.",
#          "Endometrium(mm)" = "Endometrium..mm.")
```
$~$

Here's the results after part 1 of the preparation process:
```{r}
# # merge data sets
# #pcos_data <- merge(pcos, pcos_infertility, by= "PCOS(Y/N)")
# pcos_data <- merge(pcos, pcos_infertility,  by=c("Sl.No","PCOS(Y/N)"))
# #pcos_data <- pcos_data[,-6]
# head(pcos_data)
```

```{r, echo=FALSE}
# # missing data
# colSums(is.na(pcos_data))
```

```{r, echo=FALSE, warning=FALSE}
# # convert Height from cm to m
# pcos_data$"Height(Cm)" <- round((pcos_data$"Height(Cm)" * 0.01),1)
# 
# pcos_data <- pcos_data %>% 
#   rename("Height(M)" = "Height(Cm)")
# 
# # calculate BMI
# pcos_data$BMI <- round((pcos_data$"Weight(Kg)" / pcos_data$"Height(M)"^2), 1)
# 
# # calculate waist-hip ratio
# pcos_data$"Waist-Hip Ratio" <- round((pcos_data$"Waist(inch)" / pcos_data$"Hip(inch)"),2)
# 
# # calculate FSH/LH
# pcos_data$"FSH/LH" <- round((pcos_data$"FSH(mIU/mL)"/pcos_data$"LH(mIU/mL)"),2)
# 
# # calculate Marriage Status
# pcos_data$"Marriage Status(Yrs)"[is.na(pcos_data$"Marriage Status(Yrs)")] <- median(pcos_data$"Marriage Status(Yrs)", na.rm = T)
# 
# # calculate Fast food
# pcos_data$"Fast food(Y/N)"[is.na(pcos_data$"Fast food(Y/N)")] <- median(pcos_data$"Fast food(Y/N)", na.rm = T)
# 
# # calculate 
# pcos_data$"AMH(ng/mL)"[is.na(pcos_data$"AMH(ng/mL)")] <- median(pcos_data$"AMH(ng/mL)", na.rm = T)
```

```{r}
# ggplot(pcos_data, aes(x="Age(Yrs)", y="Weight(Kg)")) +
#     geom_point() +
#   theme_ipsum() +
#     theme(
#       plot.title = element_text(size=10)
#     )
```


